create table "public"."arxiv_raw_daily" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "link" text not null,
    "published_date" date not null,
    "abstract" text not null,
    "reason" text not null
);


alter table "public"."arxiv_raw_daily" enable row level security;

CREATE UNIQUE INDEX arxiv_raw_daily_pkey ON public.arxiv_raw_daily USING btree (id);

alter table "public"."arxiv_raw_daily" add constraint "arxiv_raw_daily_pkey" PRIMARY KEY using index "arxiv_raw_daily_pkey";

grant delete on table "public"."arxiv_raw_daily" to "anon";

grant insert on table "public"."arxiv_raw_daily" to "anon";

grant references on table "public"."arxiv_raw_daily" to "anon";

grant select on table "public"."arxiv_raw_daily" to "anon";

grant trigger on table "public"."arxiv_raw_daily" to "anon";

grant truncate on table "public"."arxiv_raw_daily" to "anon";

grant update on table "public"."arxiv_raw_daily" to "anon";

grant delete on table "public"."arxiv_raw_daily" to "authenticated";

grant insert on table "public"."arxiv_raw_daily" to "authenticated";

grant references on table "public"."arxiv_raw_daily" to "authenticated";

grant select on table "public"."arxiv_raw_daily" to "authenticated";

grant trigger on table "public"."arxiv_raw_daily" to "authenticated";

grant truncate on table "public"."arxiv_raw_daily" to "authenticated";

grant update on table "public"."arxiv_raw_daily" to "authenticated";

grant delete on table "public"."arxiv_raw_daily" to "service_role";

grant insert on table "public"."arxiv_raw_daily" to "service_role";

grant references on table "public"."arxiv_raw_daily" to "service_role";

grant select on table "public"."arxiv_raw_daily" to "service_role";

grant trigger on table "public"."arxiv_raw_daily" to "service_role";

grant truncate on table "public"."arxiv_raw_daily" to "service_role";

grant update on table "public"."arxiv_raw_daily" to "service_role";

create policy "Enable read access for all users"
on "public"."arxiv_raw_daily"
as permissive
for select
to public
using (true);



